"use client";
import { createElement, useEffect, useRef, useState } from "react";
type Viewer=HTMLElement & { availableAnimations:string[];play:()=>void;pause:()=>void };
export default function ModelPreview({ src, alt }: { src: string; alt: string }) {
  const [ready,setReady]=useState(false);const [error,setError]=useState("");const [clips,setClips]=useState<string[]>([]);const [clip,setClip]=useState("");const [playing,setPlaying]=useState(true);const viewer=useRef<Viewer|null>(null);
  useEffect(()=>{let active=true;import("@google/model-viewer").then(()=>{if(active)setReady(true);}).catch(()=>{if(active)setError("The 3D viewer could not load. Download the model to inspect it in Blender.");});return()=>{active=false;};},[]);
  useEffect(()=>{const element=viewer.current;if(!element)return;setError("");setClips([]);const loaded=()=>{const names=element.availableAnimations||[];setClips(names);setClip(names[0]||"");};const failed=()=>setError("This model could not be displayed. Check the GLB in Blender or use a smaller export.");element.addEventListener("load",loaded);element.addEventListener("error",failed);return()=>{element.removeEventListener("load",loaded);element.removeEventListener("error",failed);};},[ready,src]);
  return <div><div className="model-stage">{error?<p role="alert">{error}</p>:ready?createElement("model-viewer",{ref:(element:Viewer|null)=>{viewer.current=element;},src,alt,"camera-controls":"","auto-rotate":"",autoplay:"","animation-name":clip,"shadow-intensity":"1",exposure:"1.1","environment-image":"neutral",style:{width:"100%",height:"100%",minHeight:340}}):<p role="status">Loading 3D viewer…</p>}</div>{clips.length>0&&<div className="model-animation-controls"><label>Animation <select value={clip} onChange={e=>setClip(e.target.value)}>{clips.map(name=><option value={name} key={name}>{name}</option>)}</select></label><button onClick={()=>{if(playing)viewer.current?.pause();else viewer.current?.play();setPlaying(!playing);}}>{playing?"Pause":"Play"}</button></div>}</div>;
}
