"use client";

import { useState } from "react";
import { Mail, Download, Plus, Play, Code2, Cpu, Box, FlaskConical, Layers3, Copy, Check, X, Menu, MapPin, FileText, ExternalLink } from "lucide-react";
import { Youtube, Instagram, Linkedin, Github } from "@/components/social-icons";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { assetUrl, studioUrl } from "@/lib/site-assets";
import { Services } from "@/components/services";
import { HeroCanvas } from "@/components/hero-canvas";
import { profile, projects, artworks, categories, resumes, skillGroups, experience, type Category, type Project } from "@/data/portfolio";

const socialLinks = [
  { name: "YouTube", href: profile.socials.youtube, Icon: Youtube },
  { name: "Instagram", href: profile.socials.instagram, Icon: Instagram },
  { name: "LinkedIn", href: profile.socials.linkedin, Icon: Linkedin },
  { name: "GitHub", href: profile.socials.github, Icon: Github },
];
const nav = [["Work", "work"], ["Art", "art"], ["About", "about"], ["IITaku", "iitaku"], ["Services", "services"], ["Resumes", "resumes"]];

function ProjectVisual({ project }: { project: Project }) {
  if (project.visual === "art") return <div className="project-visual render-visual"><img src={assetUrl("/art/tunnel.webp")} alt="Neon environment from Abhishek's 3D portfolio" loading="lazy" /><span className="visual-caption">BLENDER × WEBGL</span></div>;
  if (project.visual === "auc") return <div className="project-visual auc-visual"><span className="visual-caption">UCSD PED2 · ROC-AUC</span><div className="auc-row"><span>Baseline</span><div style={{ width: "67%" }} /><b>~0.67</b></div><div className="auc-row improved"><span>HPFS</span><div style={{ width: "73.4%" }} /><b>0.734</b></div><span className="chart-note">Reported model evaluation</span></div>;
  if (project.visual === "mac") return <div className="project-visual mac-visual"><span className="visual-caption">DIFFERENTIAL PHOTONIC MAC</span><div className="mac-formula"><span>Σ</span> x<sub>i</sub> · w<sub>i</sub></div><div className="mac-flow"><span>Light</span><i /><span>Weights</span><i /><span>Detect</span></div><span className="chart-note">Optical multiplication. Electronic accumulation.</span></div>;
  if (project.visual === "ring") return <div className="project-visual ring-visual"><span className="visual-caption">ADD–DROP RESONATOR · SCHEMATIC</span><svg viewBox="0 0 400 200" role="img" aria-label="Schematic of an add-drop microring resonator between two bus waveguides"><path d="M35 34H365M35 170H365" stroke="currentColor" strokeWidth="5" fill="none" /><circle cx="200" cy="102" r="54" stroke="currentColor" strokeWidth="6" fill="none" /><text x="38" y="20">INPUT</text><text x="310" y="20">THROUGH</text><text x="314" y="195">DROP</text><text x="179" y="108">Si</text></svg></div>;
  if (project.visual === "signal") return <div className="project-visual signal-visual"><span className="visual-caption">AUDIO ACQUISITION PIPELINE</span><div className="signal-chain"><span>MAX9814</span><span>ESP32</span><span>Mobile</span></div><div className="signal-spec"><b>44.1<small>kHz</small></b><div>16-bit mono<br />20–250 Hz filter</div></div></div>;
  if (project.visual === "pipeline") return <div className="project-visual pipeline-visual"><span className="visual-caption">VIDEO → STRUCTURED INPUT</span><div className="pipeline-sources"><span>CCTV</span><span>DOT</span><span>Streams</span></div><div className="pipeline-steps">Synchronize<span>·</span>Preprocess<span>·</span>Store</div><Code2 size={30} aria-hidden="true" /></div>;
  return <div className="project-visual cloud-visual"><span className="visual-caption">APPLICATION DEPLOYMENT</span><div className="cloud-names">React<span>+</span>EC2</div><div className="mac-flow"><span>Nginx</span><i /><span>TLS</span><i /><span>Cloudflare</span></div></div>;
}

function ProjectCard({ project, index }: { project: Project; index: number }) {
  return <Dialog><article className="project-card"><DialogTrigger asChild><button className="project-open" aria-label={`Read about ${project.title}`}><ProjectVisual project={project} /><div className="project-content"><div className="project-eyebrow">{project.eyebrow}</div><div className="project-heading"><h3>{project.title}</h3><span className="round-plus"><Plus size={20} /></span></div><p>{project.description}</p><div className="project-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-outcome"><span>{project.outcome}</span><span>{String(index + 1).padStart(2, "0")}</span></div></div></button></DialogTrigger></article><DialogContent className="detail-dialog"><div className="detail-category">{project.category}</div><DialogTitle className="detail-title">{project.title}</DialogTitle><DialogDescription className="detail-intro">{project.description}</DialogDescription><div className="detail-body">{project.details.map((d, i) => <p key={i}>{d}</p>)}</div><div className="project-tags">{project.tags.map(t => <span key={t}>{t}</span>)}</div>{project.links && <div className="detail-links">{project.links.map(link => <a className="button secondary" key={link.href} href={link.href} target="_blank" rel="noopener noreferrer">{link.label}<ExternalLink size={15} /></a>)}</div>}</DialogContent></Dialog>;
}

export default function Portfolio() {
  const [category, setCategory] = useState<Category>("All work");
  const [artCategory, setArtCategory] = useState("All pieces");
  const [menuOpen, setMenuOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const filtered = projects.filter(p => category === "All work" || p.category === category);
  const artFiltered = artworks.filter(a => artCategory === "All pieces" || a.type === artCategory);
  async function copyEmail() {
    try { await navigator.clipboard.writeText(profile.email); setCopied(true); setCopyError(false); setTimeout(() => setCopied(false), 2500); }
    catch { setCopyError(true); }
  }
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><div className="header-inner"><a className="wordmark" href="#home" aria-label="Abhishek Singh home"><span className="brand-mark">a<span>·</span>s</span><span>abhishek<span className="wordmark-alias"> / itsuki</span></span></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name,id]) => <a key={id} href={`#${id}`}>{name}</a>)}</nav><a className="header-contact" href="#contact">Let’s talk <Mail size={16} /></a><button className="mobile-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="mobile-nav" aria-label={menuOpen ? "Close navigation" : "Open navigation"}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{[...nav,["Contact","contact"]].map(([name,id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{name}</a>)}</nav>}</header>
    <main id="main">
      <section id="home" className="hero container">
        <HeroCanvas />
        <div className="hero-copy"><div className="eyebrow"><span className="little-star">✳</span> ENGINEER. RESEARCHER. CREATOR.</div><h1>Engineering mind.<br /><em>Creative soul.</em></h1><p className="hero-name">Abhishek Singh <span> / Itsuki · いつき</span></p><p className="hero-description">I work where AI, photonics and visual storytelling meet. Building useful systems. Exploring light. Creating worlds.</p><div className="hero-actions"><a href="#work" className="button primary">Explore my work <Layers3 size={17} /></a><a href={profile.socials.youtube} target="_blank" rel="noopener noreferrer" className="button secondary"><Play size={16} fill="currentColor" /> Meet IITaku</a></div><div className="hero-socials">{socialLinks.map(({name,href,Icon}) => <a key={name} href={href} target="_blank" rel="noopener noreferrer" aria-label={name}><Icon size={19} /></a>)}<span>IIT Patna · ECE ’27</span></div></div>
        <div className="hero-art"><div className="art-masthead"><span>THE CREATIVE SIDE</span><span>01 / SELECTED WORK</span></div><div className="hero-art-layout"><a className="hero-render" href="#art" aria-label="Explore the 3D art gallery"><img src={assetUrl("/art/tunnel.webp")} alt="Abhishek's orange and green neon 3D environment" fetchPriority="high" /><span className="image-label">Imagined. Modeled. Rendered.</span></a><a className="hero-drawing" href="#art" aria-label="Explore the illustration gallery"><img src={assetUrl("/art/portrait-drawing.webp")} alt="Anime-inspired portrait drawn by Abhishek" /><span>ILLUSTRATION</span></a><a className="hero-product" href="#art" aria-label="Explore product renders"><img src={assetUrl("/art/product.webp")} alt="Studio-lit perfume bottle from Abhishek's 3D portfolio" /><span>3D & MATERIALS</span></a></div><div className="hero-art-bottom"><span><Box size={14} /> Made in Blender & beyond</span><span className="art-signature">itsuki.</span></div></div>
      </section>
      <div className="credential-strip"><div className="container credential-inner"><div><span>IIT PATNA</span><b>B.Tech ECE</b></div><div><span>GATE ECE 2026</span><b>AIR 1046</b></div><div><span>IITAKU ON YOUTUBE</span><b>9.67K subscribers</b></div><div><span>MY PRACTICE</span><b>Code × research × art</b></div></div></div>

      <section id="work" className="section container"><div className="section-heading"><div><span className="section-number">01 / ENGINEERING & RESEARCH</span><h2>Ideas made <em>real.</em></h2></div><p>From neural networks to silicon photonics.<br />A closer look at what I build and study.</p></div><div className="filters" aria-label="Filter projects">{categories.map(c => <button key={c} onClick={() => setCategory(c)} className={category === c ? "filter active" : "filter"} aria-pressed={category === c}>{c}{c === "All work" && <span>{projects.length}</span>}</button>)}</div><div className="projects-grid" aria-live="polite">{filtered.map((p,i) => <ProjectCard key={p.id} project={p} index={i} />)}</div><div className="section-end"><span>More code, experiments and the work in progress.</span><a href={profile.socials.github} target="_blank" rel="noopener noreferrer"><Github size={16} /> GitHub / Abhishek5467</a></div></section>

      <section id="art" className="art-section"><div className="container section"><div className="section-heading"><div><span className="section-number">02 / THE OTHER SIDE OF MY BRAIN</span><h2>A little more <em>imagination.</em></h2></div><a className="text-link" href={profile.socials.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={18} /> See my Instagram</a></div><div className="art-intro"><p>3D scenes, shader experiments and illustrations. A creative practice shaped by anime, everyday objects and a fascination with light.</p><div className="filters" aria-label="Filter artworks">{["All pieces","3D & shading","Illustration"].map(c => <button key={c} className={artCategory === c ? "filter active" : "filter"} onClick={() => setArtCategory(c)} aria-pressed={artCategory === c}>{c}</button>)}</div></div><div className="art-grid" aria-live="polite">{artFiltered.map(a => <Dialog key={a.id}><DialogTrigger asChild><button className={`art-tile art-${a.id}`} aria-label={`Enlarge ${a.title}`}><img src={assetUrl(`art/${a.id}.webp`)} alt={a.alt} loading="lazy" /><span className="art-tile-caption"><span>{a.title}<small>{a.caption}</small></span><Plus size={21} /></span></button></DialogTrigger><DialogContent className="art-dialog"><DialogTitle>{a.title}</DialogTitle><DialogDescription>{a.caption} · Selection from my Instagram portfolio</DialogDescription><img src={assetUrl(`art/${a.id}.webp`)} alt={a.alt} className="lightbox-image" /><a className="text-link" href={profile.socials.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={17} /> More on Instagram</a></DialogContent></Dialog>)}</div><p className="gallery-source">Selections from my Instagram portfolio.</p></div></section>

      <section id="about" className="section container"><div className="about-grid"><div className="about-left"><span className="section-number">03 / A BIT ABOUT ME</span><h2>Curiosity is<br />the <em>common thread.</em></h2><p>I’m a final-year Electronics and Communication Engineering student at IIT Patna. I enjoy turning mathematical ideas into working code, understanding how physical systems behave, and making things that are interesting to look at.</p><p>My work spans computer vision, photonic computing, embedded systems and creative technology. Outside the lab, I draw, make 3D art, edit videos and share the process through IITaku.</p><div className="education-card"><FlaskConical size={24} /><div><h3>{profile.institution}</h3><p>{profile.degree}</p><div><span>2023–2027 · Expected</span><span>CPI {profile.cpi}</span></div></div></div><p className="affiliation">IEEE Student Member · IEEE Photonics Society<br /><span>Since June 2026</span></p></div><div className="timeline"><div className="timeline-label">EXPERIENCE & RESEARCH</div>{experience.map(e => <article key={e.role}><time>{e.date}</time><h3>{e.role}</h3><div className="timeline-place">{e.place}</div><p>{e.description}</p></article>)}</div></div><div className="skills-heading"><h3>Tools of the trade</h3><span>A mix of engineering and imagination.</span></div><div className="skills-grid">{skillGroups.map((g,i) => {const Icon=[Code2,Cpu,FlaskConical,Box][i];return <article className="skill-group" key={g.title}><Icon size={20} /><h4>{g.title}</h4><div>{g.skills.map(s => <span key={s}>{s}</span>)}</div></article>;})}</div><details className="coursework"><summary>Relevant coursework <Plus size={18} /></summary><div className="coursework-grid"><div><h4>AI & computing · completed</h4><p>Introduction to AI–ML; Programming and Data Structures; Random Signals and Stochastic Processes; Digital Signal Processing; Signals and Systems; Computer Organization and Architecture.</p></div><div><h4>Hardware & systems · completed</h4><p>Microcontroller and Embedded System; Microprocessor; Internet of Things; Digital Electronics; VLSI Design; Control Systems.</p></div><div><h4>Currently studying · October 2026</h4><p>Video Surveillance; Digital Image Processing.</p></div></div></details></section>

      <section className="achievement-section"><div className="container"><div className="achievement-heading"><span className="section-number">A FEW MILESTONES</span><h2>Built on <em>practice.</em></h2></div><div className="achievement-grid"><div><span>GATE ECE · 2026</span><b>1046</b><p>All India Rank · Score 662</p></div><div><span>JEE ADVANCED</span><b>5701</b><p>All India Rank</p></div><div><span>JEE MAIN</span><b>4311</b><p>All India Rank</p></div><div><span>PROBLEM SOLVING</span><b>1000+</b><p>Algorithm problems across judges<br /><small>Recorded in my resume</small></p></div></div><div className="cp-row"><a href={profile.socials.codeforces} target="_blank" rel="noopener noreferrer"><Code2 size={19} /><span>Codeforces <b>Pupil · peak 1241</b></span></a><a href={profile.socials.codechef} target="_blank" rel="noopener noreferrer"><Code2 size={19} /><span>CodeChef <b>3-star · peak 1643</b></span></a><a href={profile.socials.kaggle} target="_blank" rel="noopener noreferrer"><Layers3 size={19} /><span>Kaggle <b>Healthcare, finance & rainfall</b></span></a></div><div className="amazon-note"><span>Also along the way</span><p>Shortlisted for Amazon ML Summer School 2026. Participated in Kaggle competitions on problematic internet use, loan payback and rainfall prediction.</p></div></div></section>

      <section id="iitaku" className="section container"><div className="section-heading"><div><span className="section-number">04 / WHERE ENGINEERING MEETS EDITS</span><h2>Welcome to <em>IITaku.</em></h2></div><span className="channel-handle">@IITakuEdits</span></div><div className="channel-card"><div className="channel-main"><img className="channel-avatar" src={assetUrl("/art/iitaku-avatar.webp")} alt="IITaku channel mascot" loading="lazy" /><div className="channel-name">Gyan, Code &<br /><span>Anime (Toon).</span></div><p>A space for technical curiosity and creative expression. Programming, learning, anime edits and the things I make along the way.</p><a className="button youtube-button" href={profile.socials.youtube} target="_blank" rel="noopener noreferrer"><Youtube size={21} /> Visit the channel</a></div><div className="channel-side"><div className="channel-numbers"><div><b>9.67K</b><span>Subscribers</span></div><div><b>52</b><span>Videos</span></div></div><p className="metric-date">Channel snapshot · October 2026</p><div className="channel-topics"><span><Code2 size={17} /> CODE & LEARNING</span><span><Play size={17} /> ANIME & EDITS</span><span><Box size={17} /> 3D & CREATIVE WORK</span></div><div className="channel-quote">“Where Engineering<br />Meets Edits”</div><a className="text-link" href={`${profile.socials.youtube}/videos`} target="_blank" rel="noopener noreferrer"><Play size={16} /> Browse videos</a></div></div><div className="social-cards"><a href={profile.socials.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={25} /><div><h3>Instagram</h3><p>Art, renders & the creative process</p><span>@abhisheksingh_5701</span></div><ExternalLink size={17} /></a><a href={profile.socials.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={25} /><div><h3>LinkedIn</h3><p>Research, engineering & professional updates</p><span>Abhishek Singh / Itsuki</span></div><ExternalLink size={17} /></a></div></section>

      <Services />

      <section id="resumes" className="section container"><div className="section-heading"><div><span className="section-number">05 / THE DETAILS, ON PAPER</span><h2>Choose your <em>perspective.</em></h2></div><p>Six resumes, tailored to different disciplines.<br />Each opens as a PDF.</p></div><div className="resume-grid">{resumes.map(r => <article className="resume-card" key={r.file}><FileText size={22} /><h3>{r.title}</h3><p>{r.subtitle}</p><div><a href={assetUrl(`resumes/${r.file}`)} target="_blank" rel="noopener noreferrer">View PDF <ExternalLink size={14} /></a><a href={assetUrl(`resumes/${r.file}`)} download aria-label={`Download ${r.title} resume`}><Download size={19} /></a></div></article>)}</div></section>

      <section id="contact" className="contact-section"><div className="container"><span className="section-number">06 / START A CONVERSATION</span><div className="contact-heading"><h2>Have an idea?<br /><em>Let’s build it.</em></h2><p>Research collaborations, engineering projects,<br />creative work, or a problem worth solving.</p></div><div className="contact-email"><a href={`mailto:${profile.email}`}>{profile.email}</a><button onClick={copyEmail} aria-label="Copy email address">{copied ? <Check size={20} /> : <Copy size={20} />}</button></div><span className="copy-status" role="status">{copied ? "Email copied" : copyError ? "Please select the email address to copy it." : ""}</span><div className="contact-bottom"><span><MapPin size={17} /> IIT Patna · India</span><a className="button primary" href={`mailto:${profile.email}?subject=Let%E2%80%99s%20work%20together`}>Say hello <Mail size={17} /></a></div></div></section>
    </main>
    <footer className="container footer"><a className="wordmark" href="#home"><span className="brand-mark">a<span>·</span>s</span><span>abhishek / itsuki</span></a><span>© 2026 Abhishek Singh</span><div>{socialLinks.map(({name,href,Icon}) => <a key={name} href={href} target="_blank" rel="noopener noreferrer" aria-label={name}><Icon size={18} /></a>)}</div><a className="back-top" href="#home">Back to top</a></footer>
  </>;
}
