"use client";
import { useEffect, useRef, useState } from "react";
import { Box, Download, Film, ImagePlus, Upload, WandSparkles, Mail, RotateCw, X, FlaskConical, Check, FileBox } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import ModelPreview from "@/components/model-preview";
import { assetUrl } from "@/lib/site-assets";
import { PROCESSOR_URL, SHOWCASE_ONLY } from "@/lib/studio-config";
import { tabs, upscalePlans, flowPlans, products, roadmap, money, type Plan, type StudioTab } from "@/data/studio";
import { profile } from "@/data/portfolio";

type Job = { id:string; token:string; status:string; progress:number; error?:string; };
const options = (label:string,value:string,items:{value:string;label:string}[],change:(value:string)=>void) => <label className="studio-field"><span>{label}</span><Select value={value} onValueChange={change}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{items.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;
function requestLink(subject:string,body:string) { return `mailto:${profile.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; }
function saveBlob(blob:Blob,name:string) { const url=URL.createObjectURL(blob); const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000); }

function Editor({ kind }: {kind:"upscale"|"flow"}) {
  const isFlow=kind==="flow"; const plans=isFlow?flowPlans:upscalePlans;
  const [planId,setPlanId]=useState(plans[0].id);const plan=plans.find(p=>p.id===planId)!;
  const [file,setFile]=useState<File|null>(null);const [url,setUrl]=useState("");const [output,setOutput]=useState("");
  const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [job,setJob]=useState<Job|null>(null);
  const [brightness,setBrightness]=useState(100);const [contrast,setContrast]=useState(100);const [saturation,setSaturation]=useState(100);const [rotation,setRotation]=useState(0);
  const [crop,setCrop]=useState("original");const [format,setFormat]=useState("png");const [retime,setRetime]=useState("slow");
  const [dimensions,setDimensions]=useState<{width:number;height:number}>();const [duration,setDuration]=useState(0);const [start,setStart]=useState(0);const [end,setEnd]=useState(5);
  const [outputFormat,setOutputFormat]=useState("png"); const [exportKey,setExportKey]=useState(""); const input=useRef<HTMLInputElement>(null);const image=useRef<HTMLImageElement>(null);
  useEffect(()=>{if(!file){setUrl("");return;}const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next);},[file]);
  useEffect(()=>()=>{if(output)URL.revokeObjectURL(output);},[output]);
  useEffect(()=>{if(!job || !["queued","running"].includes(job.status))return;const controller=new AbortController();
    let polling=false;
    const timer=setInterval(async()=>{if(polling)return;polling=true;try{const r=await fetch(`${PROCESSOR_URL}/v1/jobs/${job.id}`,{headers:{"X-Job-Token":job.token},signal:controller.signal});const data=await r.json() as Job & {detail?:string};if(!r.ok)throw new Error(data.detail||"Could not read export status.");if(data.status==="completed"){const result=await fetch(`${PROCESSOR_URL}/v1/jobs/${job.id}/output`,{headers:{"X-Job-Token":job.token},signal:controller.signal});if(!result.ok)throw new Error("Could not download the finished export.");const blob=await result.blob();setOutput(URL.createObjectURL(blob));setBusy(false);}if(data.status==="failed"){setError(data.error||"Export failed.");setBusy(false);}if(data.status==="cancelled")setBusy(false);setJob({...data,token:job.token});}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:"Export connection failed.");setBusy(false);setJob(null);}}finally{polling=false;}},1500);
    return()=>{clearInterval(timer);controller.abort();};},[job?.id,job?.status]);
  function choose(next?:File) {setError("");setOutput("");setJob(null);if(!next)return;if(next.size>40*1024*1024){setError("Choose a file smaller than 40 MB.");return;}if(isFlow&&!next.type.startsWith("video/")){setError("Choose an MP4, WebM or supported video file.");return;}if(!isFlow&&!next.type.startsWith("image/")){setError("Choose a PNG, JPEG or WebP image.");return;}setFile(next);setStart(0);setEnd(plan.seconds||5);setDimensions(undefined);}
  async function localExport() {
    if(!file||!image.current)return;setBusy(true);setError("");setOutputFormat(format);
    try{const img=image.current;let w=img.naturalWidth,h=img.naturalHeight;let sx=0,sy=0;const ratio=crop==="square"?1:crop==="portrait"?9/16:crop==="landscape"?16/9:w/h;if(w/h>ratio){const next=h*ratio;sx=(w-next)/2;w=next;}else{const next=w/ratio;sy=(h-next)/2;h=next;}
      const rotated=rotation%180!==0;const factor=2560/Math.max(w,h);const dw=Math.max(1,Math.round(w*factor)),dh=Math.max(1,Math.round(h*factor));const canvas=document.createElement("canvas");canvas.width=rotated?dh:dw;canvas.height=rotated?dw:dh;const context=canvas.getContext("2d");if(!context)throw new Error("Image export is not available in this browser.");context.translate(canvas.width/2,canvas.height/2);context.rotate(rotation*Math.PI/180);context.filter=`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`;context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";context.drawImage(img,sx,sy,w,h,-dw/2,-dh/2,dw,dh);
      const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Could not export image.")),format==="jpg"?"image/jpeg":"image/png",.94));setOutput(URL.createObjectURL(blob));
    }catch(e){setError(e instanceof Error?e.message:"Image export failed.");}finally{setBusy(false);}
  }
  async function submitAI() {
    if(!file)return;setError("");if(SHOWCASE_ONLY){setError("Open the hosted studio to process a file.");return;}if(!PROCESSOR_URL){setError("AI processing is currently offline. You can use the free local image export or request a managed export.");return;}
    if(isFlow&&(end<=start||end-start>plan.seconds)){setError(`Select a clip of at most ${plan.seconds} seconds.`);return;}
    if(plan.price&&!exportKey){setError("Enter an export key after your managed order is confirmed, or use Request export.");return;}
    const data=new FormData();data.append("file",file);data.append("plan_id",plan.id);data.append("retime",retime);data.append("start",String(start));data.append("end",String(end));data.append("brightness",String(brightness));data.append("contrast",String(contrast));data.append("saturation",String(saturation));data.append("rotation",String(rotation));data.append("crop",crop);data.append("format",format);
    setBusy(true);setOutput("");setOutputFormat(format);try{const r=await fetch(`${PROCESSOR_URL}/v1/jobs`,{method:"POST",body:data,headers:exportKey?{Authorization:`Bearer ${exportKey}`}:{}});const result=await r.json() as Job & {detail?:string};if(!r.ok)throw new Error(result.detail||"Could not start export.");setJob(result);}catch(e){setError(e instanceof Error?e.message:"Processing connection failed.");setBusy(false);}
  }
  async function cancel() {if(!job)return;try{await fetch(`${PROCESSOR_URL}/v1/jobs/${job.id}`,{method:"DELETE",headers:{"X-Job-Token":job.token}});}finally{setBusy(false);setJob(null);}}
  const requestedBody=`I would like a ${plan.title} ${isFlow?"optical-flow":"AI upscale"} export.\nPlan: ${plan.id}\nListed pilot price: ${money(plan.price)}\nFile: ${file?.name||"I will provide the file"}\n${isFlow?`Clip: ${start}–${end}s; ${retime}; ${plan.factor}× frames`: `Output long edge: ${plan.edge}px`}\nPlease confirm availability, delivery time, payment and an export key. No payment has been made through the website.`;
  return <div className="editor-grid"><div className="editor-main"><div className="editor-toolbar"><span>{isFlow?<Film size={17}/>:<ImagePlus size={17}/>} {isFlow?"Motion workspace":"Image workspace"}</span><button onClick={()=>input.current?.click()} disabled={busy}><Upload size={16}/> Change file</button></div><input ref={input} type="file" accept={isFlow?"video/*":"image/png,image/jpeg,image/webp"} hidden onChange={e=>choose(e.target.files?.[0])}/>
    <div className={`editing-stage ${file?"has-file":""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)choose(e.dataTransfer.files[0]);}}>{!file?<button className="upload-target" onClick={()=>input.current?.click()}><Upload size={35}/><b>Drop your {isFlow?"clip":"image"} here</b><span>or choose a file · up to 40 MB</span><small>{isFlow?"MP4, WebM or a browser-supported video":"PNG, JPEG or WebP · Your preview stays on this device"}</small></button>:isFlow?<video key={url} src={output||url} controls playsInline onLoadedMetadata={e=>{if(!output){const d=e.currentTarget.duration;setDuration(d);setEnd(Math.min(d,plan.seconds));}}}/>:<img ref={image} src={url} alt="Your image preview" onLoad={e=>setDimensions({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} style={{filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`,transform:`rotate(${rotation}deg)`}}/>}</div>
    <div className="file-meta"><span>{file?.name||"No file selected"}</span><span>{isFlow?duration?`${duration.toFixed(1)} seconds`:"":dimensions?`${dimensions.width} × ${dimensions.height} px`:""}</span></div>
    {job&&<div className="job-progress"><span>{job.status} · {Math.round(job.progress)}%</span><Progress value={job.progress}/>{busy&&<button onClick={cancel}>Cancel export</button>}</div>}
    {error&&<p className="studio-error" role="alert">{error}</p>}
    {output&&<div className="export-success"><Check size={20}/><span>Your export is ready.</span><button className="button primary" onClick={async()=>{const blob=await(await fetch(output)).blob();saveBlob(blob,`iitaku-${file?.name.split(".").slice(0,-1).join(".")||"export"}.${isFlow?"mp4":outputFormat}`);}}><Download size={16}/> Download</button>{!isFlow&&<a href={output} target="_blank" rel="noopener noreferrer">View result</a>}</div>}
    <div className="editor-note"><b>{isFlow?"Independent optical-flow implementation":"Two ways to enhance an image"}</b><p>{isFlow?"Create extra frames for slow motion or smoother playback. The worker uses bidirectional Farnebäck flow and scene-cut detection. Exports are silent in this release.":"The local tool resizes and edits your image in the browser. AI super resolution uses the connected worker and a pretrained anime restoration model; it is a separate operation."}</p></div></div>
    <aside className="editor-settings"><h2>{isFlow?"Shape the motion":"Make every pixel count"}</h2><p>{isFlow?"Choose an export, then set your clip.":"Preserve the aspect ratio. Choose your output."}</p><div className="plan-options">{plans.map(p=><button key={p.id} className={p.id===planId?"plan-option selected":"plan-option"} onClick={()=>{setPlanId(p.id);if(isFlow)setEnd(Math.min(duration||p.seconds,start+p.seconds));}} disabled={busy}><span><b>{p.title}</b><small>{p.caption}</small></span><strong>{money(p.price)}</strong></button>)}</div>
    {isFlow?<><div className="trim-fields"><label>Start (seconds)<input type="number" min="0" max={duration||undefined} step=".1" value={start} onChange={e=>setStart(Math.max(0,Number(e.target.value)))}/></label><label>End (seconds)<input type="number" min="0" max={duration||undefined} step=".1" value={end} onChange={e=>setEnd(Math.max(0,Number(e.target.value)))}/></label></div>{options("Playback",retime,[{value:"slow",label:`Slow motion · ${plan.factor}× duration`},{value:"smooth",label:`Smooth playback · ${plan.factor}× FPS`}],setRetime)}</>:<><div className="adjustments">{[["Brightness",brightness,setBrightness],["Contrast",contrast,setContrast],["Saturation",saturation,setSaturation]].map(([label,value,set])=><label key={String(label)}><span>{String(label)} <b>{String(value)}%</b></span><Slider min={0} max={200} step={1} value={[Number(value)]} onValueChange={v=>(set as (n:number)=>void)(v[0])} aria-label={String(label)}/></label>)}</div><div className="settings-pair">{options("Crop",crop,[{value:"original",label:"Original"},{value:"square",label:"Square"},{value:"portrait",label:"9:16"},{value:"landscape",label:"16:9"}],setCrop)}{options("Format",format,[{value:"png",label:"PNG"},{value:"jpg",label:"JPEG"}],setFormat)}</div><button className="rotate-button" onClick={()=>setRotation((rotation+90)%360)}><RotateCw size={17}/> Rotate · {rotation}°</button></>}
    {plan.price>0&&<label className="studio-field"><span>Export key <small>after order confirmation</small></span><input type="password" value={exportKey} onChange={e=>setExportKey(e.target.value)} placeholder="Paste your export key" autoComplete="off"/></label>}
    {!isFlow&&<button className="button secondary full-button" onClick={localExport} disabled={!file||busy||SHOWCASE_ONLY}><Download size={17}/> Free local 2K export</button>}
    <button className="button primary full-button" onClick={submitAI} disabled={!file||busy||SHOWCASE_ONLY}><WandSparkles size={17}/>{busy?"Processing…":`${isFlow?"Process motion":"AI super resolution"} · ${money(plan.price)}`}</button><a className="button secondary full-button" href={requestLink(`IITaku Studio: ${plan.title} export`,requestedBody)}><Mail size={16}/> Request managed export</a>
    <p className="processor-state">{PROCESSOR_URL?"A studio processor is configured. Availability is checked when you submit.":"AI and optical-flow processing are currently offline. Local image editing is available."}</p><p className="pilot-note">Pilot prices per listed job. No unlimited processing. Requests do not collect payment or confirm an order.</p></aside></div>;
}

function Catalogue({kind}:{kind:"texture"|"asset"}) {
  const [filter,setFilter]=useState("all"); const shown=products.filter(p=>p.kind===kind&&(filter==="all"||(filter==="free"?p.price===0:p.price>0)));
  return <div><div className="catalogue-heading"><div><h2>{kind==="texture"?"Materials with a head start.":"Small assets. New worlds."}</h2><p>{kind==="texture"?"Original procedural starter packs with ready-to-use maps.":"Original modular static props for prototypes, scenes and games."}</p></div><div className="filters">{["all","free","premium"].map(f=><button className={filter===f?"filter active":"filter"} key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f.charAt(0).toUpperCase()+f.slice(1)}</button>)}</div></div><div className="catalogue-grid">{shown.map(p=><article className="product-card" key={p.id}><Dialog><DialogTrigger asChild><button className="product-preview"><img src={assetUrl(p.preview)} alt={`${p.name} preview`} loading="lazy"/><span>{p.price?"Premium starter pack":"Free · CC0"}</span></button></DialogTrigger><DialogContent className="product-dialog"><DialogTitle>{p.name}</DialogTitle><DialogDescription>{p.description} {p.specs}</DialogDescription>{p.kind==="asset"&&"model"in p&&p.model?<ModelPreview src={assetUrl(p.model)} alt={p.name}/>:<img className="product-detail-image" src={assetUrl(p.preview)} alt={`${p.name} preview`}/>}<p>{p.price?"Premium previews are public. The full-resolution files are delivered separately after an order is confirmed. Checkout is not active in this release.":"This original starter pack is CC0. You may use it in personal or commercial projects; see the licence included in the download."}</p></DialogContent></Dialog><div className="product-copy"><div><h3>{p.name}</h3><b>{money(p.price)}</b></div><p>{p.description}</p><small>{p.specs}</small><div className="project-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{!p.price?<a className="button primary full-button" href={assetUrl(p.file)} download><Download size={16}/> Download free pack</a>:<a className="button secondary full-button" href={requestLink(`IITaku Studio pack: ${p.name}`,`I would like ${p.name} (${p.id}).\nListed pilot price: ${money(p.price)}.\nPlease confirm the files, licence, availability and payment method.\nNo purchase or payment has been completed through the website.`)}><Mail size={16}/> Request pack · {money(p.price)}</a>}</div></article>)}</div></div>;
}

function BlenderBridge() {
  const [src,setSrc]=useState(assetUrl("models/crate.glb"));const [name,setName]=useState("Supply crate sample");const [error,setError]=useState("");
  useEffect(()=>()=>{if(src.startsWith("blob:"))URL.revokeObjectURL(src);},[src]);
  return <div className="blender-grid"><div><div className="editor-toolbar"><span><FileBox size={18}/> {name}</span><label className="upload-glb">Open GLB<input type="file" accept=".glb" hidden onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>50*1024*1024){setError("Use a GLB smaller than 50 MB for this browser preview.");return;}setError("");setName(f.name);setSrc(URL.createObjectURL(f));}}/></label></div><ModelPreview key={src} src={src} alt={name}/>{error&&<p role="alert" className="studio-error">{error}</p>}<p className="processor-state">Drag to orbit. Pinch or scroll to zoom. Your selected model stays in the browser.</p></div><div className="blender-instructions"><span className="section-number">FROM BLENDER TO THE WEB</span><h2>Your work, in its own dimension.</h2><ol><li><b>Prepare the scene.</b> Apply transforms, check scale, and use Principled BSDF materials or baked textures.</li><li><b>Export a GLB.</b> In Blender, use File → Export → glTF 2.0 and select GLB. Include animations if needed.</li><li><b>Preview it here.</b> Open your GLB locally and check materials, orientation and animation support.</li><li><b>Publish it.</b> Place the file in the website’s model folder and add its path to the asset catalogue or your portfolio.</li></ol><p>The source package includes a Blender export script, a local folder watcher and a detailed guide. It does not transfer a .blend file into a website automatically.</p><a className="button secondary" href={assetUrl("downloads/BLENDER_GUIDE.md")} download><Download size={17}/> Blender integration guide</a></div></div>;
}

export default function Studio() {
  const [tab,setTab]=useState<StudioTab>("upscale");
  useEffect(()=>{const params=new URLSearchParams(window.location.search||window.location.hash.split("?")[1]||"");const initial=params.get("tab");if(tabs.some(t=>t.id===initial))setTab(initial as StudioTab);},[]);
  return <div className="studio-shell"><header className="studio-header"><a href="./" className="studio-brand"><span className="brand-mark">i<span>·</span></span> IITaku <b>Studio</b></a><span className="studio-header-note">CREATE WITH INTENTION</span><a href="./">Abhishek’s portfolio</a></header><main className="studio-container"><div className="studio-title"><div><span className="section-number">TOOLS FOR THE CREATIVE SIDE</span><h1>Your work. <em>More possibility.</em></h1></div><span className="release-pill">Creator toolkit · v1.0</span></div>{SHOWCASE_ONLY&&<p className="studio-error">This is a portfolio demonstration. Open the separately hosted studio for processing and commercial services.</p>}<Tabs value={tab} onValueChange={value=>setTab(value as StudioTab)}><TabsList className="studio-tabs">{tabs.map(t=><TabsTrigger value={t.id} key={t.id}>{t.title}</TabsTrigger>)}</TabsList><TabsContent forceMount value="upscale"><Editor kind="upscale"/></TabsContent><TabsContent forceMount value="flow"><Editor kind="flow"/></TabsContent><TabsContent value="textures"><Catalogue kind="texture"/></TabsContent><TabsContent value="assets"><Catalogue kind="asset"/></TabsContent><TabsContent value="blender"><BlenderBridge/></TabsContent><TabsContent value="roadmap"><div className="roadmap-heading"><FlaskConical size={28}/><h2>From a toolkit to a reconstruction lab.</h2><p>Low-poly-to-high-detail learning is an experiment. Geometry refinement, textures, UVs, rigs and animation each need their own validation.</p></div><div className="roadmap-grid">{roadmap.map(r=><article key={r.version}><span>{r.version} / {r.status}</span><h3>{r.title}</h3><p>{r.details}</p></article>)}</div><div className="training-card"><h3>A first 30-hour Kaggle experiment</h3><p>Start with original meshes or a rights-reviewed subset. Create high / decimated low pairs, split by source object, prepare signed-distance grids on CPU, then train a compact residual 3D network. Keep a subdivision baseline and held-out Chamfer / normal metrics.</p><a href={assetUrl("downloads/TRAINING_PLAN.md")} download className="button secondary"><Download size={17}/> Read the training plan</a><span>Training source and notebook are included in the downloadable project package.</span></div></TabsContent></Tabs></main><footer className="studio-footer"><span>© 2026 Abhishek Singh / IITaku</span><span>Local editing · Original starter assets · Experimental reconstruction</span><a href={`mailto:${profile.email}`}>Contact the studio</a></footer></div>;
}
